### ISSUE TITLE
Replacement for seer.r-pkg.org:9200

### ISSUE THREAD

**Issue by remyd1** [r-hub/search#5]
Hi,

I am looking for a replacement of the service in the title (as it seems to be down) and I think I am in the right place.

Is there any public search service available to avoid to install our own search instance ?

Indeed, I need to access it through PHP with a web API or JSON service like previously with `http://seer.r-pkg.org:9200`. Obviously, I also need to avoid the use of the `pkgsearch` R package.

Thanks,

**Comment by gaborcsardi** [comment]
See http://search.r-pkg.org/ and the pkgsearch source code how it is used.

**Comment by remyd1** [comment]
Thanks @gaborcsardi 

Indeed, I was just going to answer that I found the solution in the `pkgsearch` source code ([here](https://github.com/r-hub/pkgsearch/blob/master/R/api.R#L73)).

Best regards,

PS : for example `http://search.r-pkg.org/package/_search?size=30&q=Package:dplyr*`
